name: Judge Submission

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      code:
        required: true
        type: string
      challenge_name:
        required: true
        type: string
      submission_id:
        required: true
        type: string
      judge_webhook:
        required: true
        type: string

jobs:
  judge:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Clone challenge repo
        run: |
          git clone ${{ github.event.inputs.repo }} challenge

      - name: Inject user code
        run: |
          echo "${{ github.event.inputs.code }}" > challenge/${{ github.event.inputs.challenge_name }}/src/index.ts

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd challenge/${{ github.event.inputs.challenge_name }}
          npm install

      - name: Run tests
        run: |
          cd challenge/${{ github.event.inputs.challenge_name }}
          npm run test

      - name: Update webhook
        run: |
          cd challenge/${{ github.event.inputs.challenge_name }}
          RESULTS=$(cat test-summary.txt | tr -d '\n')
          curl -X POST ${{ github.event.inputs.judge_webhook }} \
          -H "Content-Type: application/json" \
          -d '{
            "submissionId" : "${{ github.event.inputs.submission_id }}",
            "results": "'"$RESULTS"'"
          }'
